package com.sh3h.localprovider.greendaoDao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.sh3h.localprovider.greendaoEntity.BranchAccept;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "BZ_BRANCH_ACCEPT".
*/
public class BranchAcceptDao extends AbstractDao<BranchAccept, Long> {

    public static final String TABLENAME = "BZ_BRANCH_ACCEPT";

    /**
     * Properties of entity BranchAccept.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property ACCEPT_ID = new Property(0, Long.class, "ACCEPT_ID", true, "ACCEPT_ID");
        public final static Property SERVER_ID = new Property(1, Long.class, "SERVER_ID", false, "SERVER_ID");
        public final static Property PROJECT_ID = new Property(2, long.class, "PROJECT_ID", false, "PROJECT_ID");
        public final static Property BUDGET_ID = new Property(3, long.class, "BUDGET_ID", false, "BUDGET_ID");
        public final static Property CHECK_SITUATION = new Property(4, String.class, "CHECK_SITUATION", false, "CHECK_SITUATION");
        public final static Property LEAK_SITUATION = new Property(5, String.class, "LEAK_SITUATION", false, "LEAK_SITUATION");
        public final static Property LEAK_REFORM = new Property(6, String.class, "LEAK_REFORM", false, "LEAK_REFORM");
        public final static Property OPERATOR = new Property(7, String.class, "OPERATOR", false, "OPERATOR");
        public final static Property OPERATE_TIME = new Property(8, long.class, "OPERATE_TIME", false, "OPERATE_TIME");
        public final static Property LONGITUDE = new Property(9, double.class, "LONGITUDE", false, "LONGITUDE");
        public final static Property LATITUDE = new Property(10, double.class, "LATITUDE", false, "LATITUDE");
        public final static Property REMARK = new Property(11, String.class, "REMARK", false, "REMARK");
        public final static Property UPLOAD = new Property(12, int.class, "UPLOAD", false, "UPLOAD");
        public final static Property ACCEPT_TYPE = new Property(13, int.class, "ACCEPT_TYPE", false, "ACCEPT__TYPE");
    }


    public BranchAcceptDao(DaoConfig config) {
        super(config);
    }
    
    public BranchAcceptDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"BZ_BRANCH_ACCEPT\" (" + //
                "\"ACCEPT_ID\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: ACCEPT_ID
                "\"SERVER_ID\" INTEGER," + // 1: SERVER_ID
                "\"PROJECT_ID\" INTEGER NOT NULL ," + // 2: PROJECT_ID
                "\"BUDGET_ID\" INTEGER NOT NULL ," + // 3: BUDGET_ID
                "\"CHECK_SITUATION\" TEXT," + // 4: CHECK_SITUATION
                "\"LEAK_SITUATION\" TEXT," + // 5: LEAK_SITUATION
                "\"LEAK_REFORM\" TEXT," + // 6: LEAK_REFORM
                "\"OPERATOR\" TEXT," + // 7: OPERATOR
                "\"OPERATE_TIME\" INTEGER NOT NULL ," + // 8: OPERATE_TIME
                "\"LONGITUDE\" REAL NOT NULL ," + // 9: LONGITUDE
                "\"LATITUDE\" REAL NOT NULL ," + // 10: LATITUDE
                "\"REMARK\" TEXT," + // 11: REMARK
                "\"UPLOAD\" INTEGER NOT NULL ," + // 12: UPLOAD
                "\"ACCEPT__TYPE\" INTEGER NOT NULL );"); // 13: ACCEPT_TYPE
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"BZ_BRANCH_ACCEPT\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, BranchAccept entity) {
        stmt.clearBindings();
 
        Long ACCEPT_ID = entity.getACCEPT_ID();
        if (ACCEPT_ID != null) {
            stmt.bindLong(1, ACCEPT_ID);
        }
 
        Long SERVER_ID = entity.getSERVER_ID();
        if (SERVER_ID != null) {
            stmt.bindLong(2, SERVER_ID);
        }
        stmt.bindLong(3, entity.getPROJECT_ID());
        stmt.bindLong(4, entity.getBUDGET_ID());
 
        String CHECK_SITUATION = entity.getCHECK_SITUATION();
        if (CHECK_SITUATION != null) {
            stmt.bindString(5, CHECK_SITUATION);
        }
 
        String LEAK_SITUATION = entity.getLEAK_SITUATION();
        if (LEAK_SITUATION != null) {
            stmt.bindString(6, LEAK_SITUATION);
        }
 
        String LEAK_REFORM = entity.getLEAK_REFORM();
        if (LEAK_REFORM != null) {
            stmt.bindString(7, LEAK_REFORM);
        }
 
        String OPERATOR = entity.getOPERATOR();
        if (OPERATOR != null) {
            stmt.bindString(8, OPERATOR);
        }
        stmt.bindLong(9, entity.getOPERATE_TIME());
        stmt.bindDouble(10, entity.getLONGITUDE());
        stmt.bindDouble(11, entity.getLATITUDE());
 
        String REMARK = entity.getREMARK();
        if (REMARK != null) {
            stmt.bindString(12, REMARK);
        }
        stmt.bindLong(13, entity.getUPLOAD());
        stmt.bindLong(14, entity.getACCEPT_TYPE());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, BranchAccept entity) {
        stmt.clearBindings();
 
        Long ACCEPT_ID = entity.getACCEPT_ID();
        if (ACCEPT_ID != null) {
            stmt.bindLong(1, ACCEPT_ID);
        }
 
        Long SERVER_ID = entity.getSERVER_ID();
        if (SERVER_ID != null) {
            stmt.bindLong(2, SERVER_ID);
        }
        stmt.bindLong(3, entity.getPROJECT_ID());
        stmt.bindLong(4, entity.getBUDGET_ID());
 
        String CHECK_SITUATION = entity.getCHECK_SITUATION();
        if (CHECK_SITUATION != null) {
            stmt.bindString(5, CHECK_SITUATION);
        }
 
        String LEAK_SITUATION = entity.getLEAK_SITUATION();
        if (LEAK_SITUATION != null) {
            stmt.bindString(6, LEAK_SITUATION);
        }
 
        String LEAK_REFORM = entity.getLEAK_REFORM();
        if (LEAK_REFORM != null) {
            stmt.bindString(7, LEAK_REFORM);
        }
 
        String OPERATOR = entity.getOPERATOR();
        if (OPERATOR != null) {
            stmt.bindString(8, OPERATOR);
        }
        stmt.bindLong(9, entity.getOPERATE_TIME());
        stmt.bindDouble(10, entity.getLONGITUDE());
        stmt.bindDouble(11, entity.getLATITUDE());
 
        String REMARK = entity.getREMARK();
        if (REMARK != null) {
            stmt.bindString(12, REMARK);
        }
        stmt.bindLong(13, entity.getUPLOAD());
        stmt.bindLong(14, entity.getACCEPT_TYPE());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public BranchAccept readEntity(Cursor cursor, int offset) {
        BranchAccept entity = new BranchAccept( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // ACCEPT_ID
            cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1), // SERVER_ID
            cursor.getLong(offset + 2), // PROJECT_ID
            cursor.getLong(offset + 3), // BUDGET_ID
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // CHECK_SITUATION
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // LEAK_SITUATION
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // LEAK_REFORM
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // OPERATOR
            cursor.getLong(offset + 8), // OPERATE_TIME
            cursor.getDouble(offset + 9), // LONGITUDE
            cursor.getDouble(offset + 10), // LATITUDE
            cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11), // REMARK
            cursor.getInt(offset + 12), // UPLOAD
            cursor.getInt(offset + 13) // ACCEPT_TYPE
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, BranchAccept entity, int offset) {
        entity.setACCEPT_ID(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setSERVER_ID(cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1));
        entity.setPROJECT_ID(cursor.getLong(offset + 2));
        entity.setBUDGET_ID(cursor.getLong(offset + 3));
        entity.setCHECK_SITUATION(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setLEAK_SITUATION(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setLEAK_REFORM(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setOPERATOR(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setOPERATE_TIME(cursor.getLong(offset + 8));
        entity.setLONGITUDE(cursor.getDouble(offset + 9));
        entity.setLATITUDE(cursor.getDouble(offset + 10));
        entity.setREMARK(cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11));
        entity.setUPLOAD(cursor.getInt(offset + 12));
        entity.setACCEPT_TYPE(cursor.getInt(offset + 13));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(BranchAccept entity, long rowId) {
        entity.setACCEPT_ID(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(BranchAccept entity) {
        if(entity != null) {
            return entity.getACCEPT_ID();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(BranchAccept entity) {
        return entity.getACCEPT_ID() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
