package com.sh3h.localprovider.greendaoDao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.sh3h.localprovider.greendaoEntity.MaterialVerify;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "BZ_MATERIAL_VERIFY".
*/
public class MaterialVerifyDao extends AbstractDao<MaterialVerify, Long> {

    public static final String TABLENAME = "BZ_MATERIAL_VERIFY";

    /**
     * Properties of entity MaterialVerify.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property VERIFY_ID = new Property(0, Long.class, "VERIFY_ID", true, "VERIFY_ID");
        public final static Property SERVER_ID = new Property(1, Long.class, "SERVER_ID", false, "SERVER_ID");
        public final static Property MATERIAL_ID = new Property(2, long.class, "MATERIAL_ID", false, "MATERIAL_ID");
        public final static Property DELIVERY_NUMBER = new Property(3, String.class, "DELIVERY_NUMBER", false, "DELIVERY_NUMBER");
        public final static Property CONSTRUCTION_TEAM = new Property(4, String.class, "CONSTRUCTION_TEAM", false, "CONSTRUCTION_TEAM");
        public final static Property VERIFY_COUNT = new Property(5, float.class, "VERIFY_COUNT", false, "VERIFY_COUNT");
        public final static Property OPERATOR = new Property(6, String.class, "OPERATOR", false, "OPERATOR");
        public final static Property OPERATE_TIME = new Property(7, long.class, "OPERATE_TIME", false, "OPERATE_TIME");
        public final static Property LONGITUDE = new Property(8, double.class, "LONGITUDE", false, "LONGITUDE");
        public final static Property LATITUDE = new Property(9, double.class, "LATITUDE", false, "LATITUDE");
        public final static Property REMARK = new Property(10, String.class, "REMARK", false, "REMARK");
        public final static Property UPLOAD = new Property(11, int.class, "UPLOAD", false, "UPLOAD");
    }


    public MaterialVerifyDao(DaoConfig config) {
        super(config);
    }
    
    public MaterialVerifyDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"BZ_MATERIAL_VERIFY\" (" + //
                "\"VERIFY_ID\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: VERIFY_ID
                "\"SERVER_ID\" INTEGER," + // 1: SERVER_ID
                "\"MATERIAL_ID\" INTEGER NOT NULL ," + // 2: MATERIAL_ID
                "\"DELIVERY_NUMBER\" TEXT," + // 3: DELIVERY_NUMBER
                "\"CONSTRUCTION_TEAM\" TEXT," + // 4: CONSTRUCTION_TEAM
                "\"VERIFY_COUNT\" REAL NOT NULL ," + // 5: VERIFY_COUNT
                "\"OPERATOR\" TEXT," + // 6: OPERATOR
                "\"OPERATE_TIME\" INTEGER NOT NULL ," + // 7: OPERATE_TIME
                "\"LONGITUDE\" REAL NOT NULL ," + // 8: LONGITUDE
                "\"LATITUDE\" REAL NOT NULL ," + // 9: LATITUDE
                "\"REMARK\" TEXT," + // 10: REMARK
                "\"UPLOAD\" INTEGER NOT NULL );"); // 11: UPLOAD
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"BZ_MATERIAL_VERIFY\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, MaterialVerify entity) {
        stmt.clearBindings();
 
        Long VERIFY_ID = entity.getVERIFY_ID();
        if (VERIFY_ID != null) {
            stmt.bindLong(1, VERIFY_ID);
        }
 
        Long SERVER_ID = entity.getSERVER_ID();
        if (SERVER_ID != null) {
            stmt.bindLong(2, SERVER_ID);
        }
        stmt.bindLong(3, entity.getMATERIAL_ID());
 
        String DELIVERY_NUMBER = entity.getDELIVERY_NUMBER();
        if (DELIVERY_NUMBER != null) {
            stmt.bindString(4, DELIVERY_NUMBER);
        }
 
        String CONSTRUCTION_TEAM = entity.getCONSTRUCTION_TEAM();
        if (CONSTRUCTION_TEAM != null) {
            stmt.bindString(5, CONSTRUCTION_TEAM);
        }
        stmt.bindDouble(6, entity.getVERIFY_COUNT());
 
        String OPERATOR = entity.getOPERATOR();
        if (OPERATOR != null) {
            stmt.bindString(7, OPERATOR);
        }
        stmt.bindLong(8, entity.getOPERATE_TIME());
        stmt.bindDouble(9, entity.getLONGITUDE());
        stmt.bindDouble(10, entity.getLATITUDE());
 
        String REMARK = entity.getREMARK();
        if (REMARK != null) {
            stmt.bindString(11, REMARK);
        }
        stmt.bindLong(12, entity.getUPLOAD());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, MaterialVerify entity) {
        stmt.clearBindings();
 
        Long VERIFY_ID = entity.getVERIFY_ID();
        if (VERIFY_ID != null) {
            stmt.bindLong(1, VERIFY_ID);
        }
 
        Long SERVER_ID = entity.getSERVER_ID();
        if (SERVER_ID != null) {
            stmt.bindLong(2, SERVER_ID);
        }
        stmt.bindLong(3, entity.getMATERIAL_ID());
 
        String DELIVERY_NUMBER = entity.getDELIVERY_NUMBER();
        if (DELIVERY_NUMBER != null) {
            stmt.bindString(4, DELIVERY_NUMBER);
        }
 
        String CONSTRUCTION_TEAM = entity.getCONSTRUCTION_TEAM();
        if (CONSTRUCTION_TEAM != null) {
            stmt.bindString(5, CONSTRUCTION_TEAM);
        }
        stmt.bindDouble(6, entity.getVERIFY_COUNT());
 
        String OPERATOR = entity.getOPERATOR();
        if (OPERATOR != null) {
            stmt.bindString(7, OPERATOR);
        }
        stmt.bindLong(8, entity.getOPERATE_TIME());
        stmt.bindDouble(9, entity.getLONGITUDE());
        stmt.bindDouble(10, entity.getLATITUDE());
 
        String REMARK = entity.getREMARK();
        if (REMARK != null) {
            stmt.bindString(11, REMARK);
        }
        stmt.bindLong(12, entity.getUPLOAD());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public MaterialVerify readEntity(Cursor cursor, int offset) {
        MaterialVerify entity = new MaterialVerify( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // VERIFY_ID
            cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1), // SERVER_ID
            cursor.getLong(offset + 2), // MATERIAL_ID
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // DELIVERY_NUMBER
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // CONSTRUCTION_TEAM
            cursor.getFloat(offset + 5), // VERIFY_COUNT
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // OPERATOR
            cursor.getLong(offset + 7), // OPERATE_TIME
            cursor.getDouble(offset + 8), // LONGITUDE
            cursor.getDouble(offset + 9), // LATITUDE
            cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10), // REMARK
            cursor.getInt(offset + 11) // UPLOAD
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, MaterialVerify entity, int offset) {
        entity.setVERIFY_ID(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setSERVER_ID(cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1));
        entity.setMATERIAL_ID(cursor.getLong(offset + 2));
        entity.setDELIVERY_NUMBER(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setCONSTRUCTION_TEAM(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setVERIFY_COUNT(cursor.getFloat(offset + 5));
        entity.setOPERATOR(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setOPERATE_TIME(cursor.getLong(offset + 7));
        entity.setLONGITUDE(cursor.getDouble(offset + 8));
        entity.setLATITUDE(cursor.getDouble(offset + 9));
        entity.setREMARK(cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10));
        entity.setUPLOAD(cursor.getInt(offset + 11));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(MaterialVerify entity, long rowId) {
        entity.setVERIFY_ID(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(MaterialVerify entity) {
        if(entity != null) {
            return entity.getVERIFY_ID();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(MaterialVerify entity) {
        return entity.getVERIFY_ID() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
