package com.sh3h.localprovider.greendaoDao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.sh3h.localprovider.greendaoEntity.Patrol;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "BZ_PATROL".
*/
public class PatrolDao extends AbstractDao<Patrol, Long> {

    public static final String TABLENAME = "BZ_PATROL";

    /**
     * Properties of entity Patrol.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property PATROL_ID = new Property(0, Long.class, "PATROL_ID", true, "PATROL_ID");
        public final static Property SERVER_ID = new Property(1, Long.class, "SERVER_ID", false, "SERVER_ID");
        public final static Property PROJECT_ID = new Property(2, long.class, "PROJECT_ID", false, "PROJECT_ID");
        public final static Property VIOLATION_NUMBER = new Property(3, long.class, "VIOLATION_NUMBER", false, "VIOLATION_NUMBER");
        public final static Property PATROL_SITUATION = new Property(4, String.class, "PATROL_SITUATION", false, "PATROL_SITUATION");
        public final static Property PATROL_TYPE = new Property(5, int.class, "PATROL_TYPE", false, "PATROL_TYPE");
        public final static Property OPERATOR = new Property(6, String.class, "OPERATOR", false, "OPERATOR");
        public final static Property OPERATE_TIME = new Property(7, long.class, "OPERATE_TIME", false, "OPERATE_TIME");
        public final static Property LONGITUDE = new Property(8, double.class, "LONGITUDE", false, "LONGITUDE");
        public final static Property LATITUDE = new Property(9, double.class, "LATITUDE", false, "LATITUDE");
        public final static Property REMARK = new Property(10, String.class, "REMARK", false, "REMARK");
        public final static Property UPLOAD = new Property(11, int.class, "UPLOAD", false, "UPLOAD");
    }


    public PatrolDao(DaoConfig config) {
        super(config);
    }
    
    public PatrolDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"BZ_PATROL\" (" + //
                "\"PATROL_ID\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: PATROL_ID
                "\"SERVER_ID\" INTEGER," + // 1: SERVER_ID
                "\"PROJECT_ID\" INTEGER NOT NULL ," + // 2: PROJECT_ID
                "\"VIOLATION_NUMBER\" INTEGER NOT NULL ," + // 3: VIOLATION_NUMBER
                "\"PATROL_SITUATION\" TEXT," + // 4: PATROL_SITUATION
                "\"PATROL_TYPE\" INTEGER NOT NULL ," + // 5: PATROL_TYPE
                "\"OPERATOR\" TEXT," + // 6: OPERATOR
                "\"OPERATE_TIME\" INTEGER NOT NULL ," + // 7: OPERATE_TIME
                "\"LONGITUDE\" REAL NOT NULL ," + // 8: LONGITUDE
                "\"LATITUDE\" REAL NOT NULL ," + // 9: LATITUDE
                "\"REMARK\" TEXT," + // 10: REMARK
                "\"UPLOAD\" INTEGER NOT NULL );"); // 11: UPLOAD
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"BZ_PATROL\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Patrol entity) {
        stmt.clearBindings();
 
        Long PATROL_ID = entity.getPATROL_ID();
        if (PATROL_ID != null) {
            stmt.bindLong(1, PATROL_ID);
        }
 
        Long SERVER_ID = entity.getSERVER_ID();
        if (SERVER_ID != null) {
            stmt.bindLong(2, SERVER_ID);
        }
        stmt.bindLong(3, entity.getPROJECT_ID());
        stmt.bindLong(4, entity.getVIOLATION_NUMBER());
 
        String PATROL_SITUATION = entity.getPATROL_SITUATION();
        if (PATROL_SITUATION != null) {
            stmt.bindString(5, PATROL_SITUATION);
        }
        stmt.bindLong(6, entity.getPATROL_TYPE());
 
        String OPERATOR = entity.getOPERATOR();
        if (OPERATOR != null) {
            stmt.bindString(7, OPERATOR);
        }
        stmt.bindLong(8, entity.getOPERATE_TIME());
        stmt.bindDouble(9, entity.getLONGITUDE());
        stmt.bindDouble(10, entity.getLATITUDE());
 
        String REMARK = entity.getREMARK();
        if (REMARK != null) {
            stmt.bindString(11, REMARK);
        }
        stmt.bindLong(12, entity.getUPLOAD());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Patrol entity) {
        stmt.clearBindings();
 
        Long PATROL_ID = entity.getPATROL_ID();
        if (PATROL_ID != null) {
            stmt.bindLong(1, PATROL_ID);
        }
 
        Long SERVER_ID = entity.getSERVER_ID();
        if (SERVER_ID != null) {
            stmt.bindLong(2, SERVER_ID);
        }
        stmt.bindLong(3, entity.getPROJECT_ID());
        stmt.bindLong(4, entity.getVIOLATION_NUMBER());
 
        String PATROL_SITUATION = entity.getPATROL_SITUATION();
        if (PATROL_SITUATION != null) {
            stmt.bindString(5, PATROL_SITUATION);
        }
        stmt.bindLong(6, entity.getPATROL_TYPE());
 
        String OPERATOR = entity.getOPERATOR();
        if (OPERATOR != null) {
            stmt.bindString(7, OPERATOR);
        }
        stmt.bindLong(8, entity.getOPERATE_TIME());
        stmt.bindDouble(9, entity.getLONGITUDE());
        stmt.bindDouble(10, entity.getLATITUDE());
 
        String REMARK = entity.getREMARK();
        if (REMARK != null) {
            stmt.bindString(11, REMARK);
        }
        stmt.bindLong(12, entity.getUPLOAD());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public Patrol readEntity(Cursor cursor, int offset) {
        Patrol entity = new Patrol( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // PATROL_ID
            cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1), // SERVER_ID
            cursor.getLong(offset + 2), // PROJECT_ID
            cursor.getLong(offset + 3), // VIOLATION_NUMBER
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // PATROL_SITUATION
            cursor.getInt(offset + 5), // PATROL_TYPE
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // OPERATOR
            cursor.getLong(offset + 7), // OPERATE_TIME
            cursor.getDouble(offset + 8), // LONGITUDE
            cursor.getDouble(offset + 9), // LATITUDE
            cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10), // REMARK
            cursor.getInt(offset + 11) // UPLOAD
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Patrol entity, int offset) {
        entity.setPATROL_ID(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setSERVER_ID(cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1));
        entity.setPROJECT_ID(cursor.getLong(offset + 2));
        entity.setVIOLATION_NUMBER(cursor.getLong(offset + 3));
        entity.setPATROL_SITUATION(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setPATROL_TYPE(cursor.getInt(offset + 5));
        entity.setOPERATOR(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setOPERATE_TIME(cursor.getLong(offset + 7));
        entity.setLONGITUDE(cursor.getDouble(offset + 8));
        entity.setLATITUDE(cursor.getDouble(offset + 9));
        entity.setREMARK(cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10));
        entity.setUPLOAD(cursor.getInt(offset + 11));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Patrol entity, long rowId) {
        entity.setPATROL_ID(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Patrol entity) {
        if(entity != null) {
            return entity.getPATROL_ID();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Patrol entity) {
        return entity.getPATROL_ID() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
